name: Build and Deploy WAR to Tomcat

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Build and Deploy to External Tomcat
    runs-on: ubuntu-latest
    environment: springboot-app-tomcate

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Inject finalName from secret into pom.xml
        run: |
          sed -i '/<build>/a \ \ \ \ <finalName>${{ secrets.APP_NAME }}</finalName>' pom.xml

      - name: Build WAR using Maven
        run: mvn clean package --file pom.xml

      - name: Deploy WAR to Tomcat
        run: |
          curl --upload-file target/${{ secrets.APP_NAME }}.war \
            "http://${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}@${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/${{ secrets.APP_NAME }}&update=true"
